# A map to all frames
module.exports =
  moment: require './moment'
  thought: require './thought'
  dream: require './dream'
  wish: require './wish'
  search: require './search'
  drink: require './drink'
  text: require './text'
  laugh: require './laugh'
  flirt: require './flirt'
  kiss: require './kiss'
  lie: require './lie'
  breakup: require './breakup'
  game: require './game'
  success: require './success'
  failure: require './failure'
  better: require './better'
  year: require './year'